import {
  SiJavascript, SiTypescript, SiReact, SiVuedotjs, SiNextdotjs, SiAngular, SiSvelte, SiTailwindcss,
  SiNodedotjs, SiExpress, SiOpenjdk, SiSpring, SiPython, SiDjango, SiFlask, SiFastapi,
  SiRuby, SiRubyonrails, SiPhp, SiLaravel, SiCplusplus, SiDotnet, SiGo, SiRust, SiScala,
  SiTensorflow, SiPytorch, SiPandas,
  SiMysql, SiPostgresql, SiMongodb, SiRedis, SiGraphql, SiFirebase, SiElasticsearch,
  SiDocker, SiKubernetes, SiGit, SiLinux, SiTerraform,
  SiSwift, SiKotlin, SiFlutter,
  SiFigma, SiUnity, SiUnrealengine,
} from "react-icons/si";
import { FaAws } from "react-icons/fa";

// Map tech name → brand color
export const TECH_COLOR = {
  // Frontend
  "JavaScript":    "#F7DF1E",
  "TypeScript":    "#3178C6",
  "React":         "#61DAFB",
  "Vue":           "#42B883",
  "Next.js":       "#000000",
  "Angular":       "#DD0031",
  "Svelte":        "#FF3E00",
  "Tailwind CSS":  "#06B6D4",
  // Backend
  "Node.js":       "#539E43",
  "Express.js":    "#000000",
  "Java":          "#E11D2C",
  "Spring":        "#6DB33F",
  "Python":        "#3572A5",
  "Django":        "#092E20",
  "Flask":         "#000000",
  "FastAPI":       "#009688",
  "Ruby":          "#CC342D",
  "Ruby on Rails": "#CC0000",
  "PHP":           "#777BB4",
  "Laravel":       "#FF2D20",
  "C++":           "#00599C",
  "C#":            "#512BD4",
  "Go":            "#00ACD7",
  "Rust":          "#DEA584",
  "Scala":         "#DC322F",
  // ML / AI
  "TensorFlow":    "#FF6F00",
  "PyTorch":       "#EE4C2C",
  "Pandas":        "#150458",
  // Database
  "SQL":           "#4479A1",
  "MySQL":         "#4479A1",
  "PostgreSQL":    "#336791",
  "Postgres":      "#336791",
  "MongoDB":       "#47A248",
  "Redis":         "#DC382D",
  "GraphQL":       "#E10098",
  "Firebase":      "#FFCA28",
  "Elasticsearch": "#005571",
  // DevOps / Cloud
  "AWS":           "#FF9900",
  "Docker":        "#2496ED",
  "Kubernetes":    "#326CE5",
  "Git":           "#F05032",
  "Linux":         "#FCC624",
  "Terraform":     "#7B42BC",
  // Mobile
  "Swift":         "#FA7343",
  "Kotlin":        "#7F52FF",
  "Flutter":       "#02569B",
  "React Native":  "#61DAFB",
  // Design / Game
  "Figma":         "#F24E1E",
  "UI/UX":         "#F24E1E",
  "Unity":         "#000000",
  "Unreal Engine": "#0D1117",
};

// Map tech name → react-icons component (call with <Icon size={n} />)
export const TECH_ICON = {
  // Frontend
  "JavaScript":    SiJavascript,
  "TypeScript":    SiTypescript,
  "React":         SiReact,
  "Vue":           SiVuedotjs,
  "Next.js":       SiNextdotjs,
  "Angular":       SiAngular,
  "Svelte":        SiSvelte,
  "Tailwind CSS":  SiTailwindcss,
  // Backend
  "Node.js":       SiNodedotjs,
  "Express.js":    SiExpress,
  "Java":          SiOpenjdk,
  "Spring":        SiSpring,
  "Python":        SiPython,
  "Django":        SiDjango,
  "Flask":         SiFlask,
  "FastAPI":       SiFastapi,
  "Ruby":          SiRuby,
  "Ruby on Rails": SiRubyonrails,
  "PHP":           SiPhp,
  "Laravel":       SiLaravel,
  "C++":           SiCplusplus,
  "C#":            SiDotnet,
  "Go":            SiGo,
  "Rust":          SiRust,
  "Scala":         SiScala,
  // ML / AI
  "TensorFlow":    SiTensorflow,
  "PyTorch":       SiPytorch,
  "Pandas":        SiPandas,
  // Database
  "SQL":           SiMysql,
  "MySQL":         SiMysql,
  "PostgreSQL":    SiPostgresql,
  "Postgres":      SiPostgresql,
  "MongoDB":       SiMongodb,
  "Redis":         SiRedis,
  "GraphQL":       SiGraphql,
  "Firebase":      SiFirebase,
  "Elasticsearch": SiElasticsearch,
  // DevOps / Cloud
  "AWS":           FaAws,
  "Docker":        SiDocker,
  "Kubernetes":    SiKubernetes,
  "Git":           SiGit,
  "Linux":         SiLinux,
  "Terraform":     SiTerraform,
  // Mobile
  "Swift":         SiSwift,
  "Kotlin":        SiKotlin,
  "Flutter":       SiFlutter,
  "React Native":  SiReact,
  // Design / Game
  "Figma":         SiFigma,
  "UI/UX":         SiFigma,
  "Unity":         SiUnity,
  "Unreal Engine": SiUnrealengine,
};
